### ISSUE TITLE
Any releases?

### ISSUE THREAD

**Issue by edent** [detjonmataj/Data-Structure-and-Algorithms-Visualization-in-VR#19]
Are there any APKs which I can install on the Quest 2?

Thanks 😄

**Comment by detjonmataj** [comment]
Yes, there is 1 pre-release available which I haven't fully tested.

Thanks for your interest 😄!

P.S.
It's one of my concept projects that I've been working on to explore virtual technologies, so don't expect much from it. It would be great if I could scale it and create a new learning platform in VR, but currently is discontinued.
